export const categoriesData = [
  {
    name: 'Starters & Tapas',
    slug: 'starters',
    description: 'Crisp, flavorful openers to kickstart your culinary journey.',
    icon: 'Utensils',
    image: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=600&q=80',
    displayOrder: 1,
  },
  {
    name: 'Artisanal Pizzas',
    slug: 'pizzas',
    description: 'Wood-fired sourdough crusts with fresh San Marzano tomatoes & fior di latte.',
    icon: 'Pizza',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
    displayOrder: 2,
  },
  {
    name: 'Gourmet Mains & Grills',
    slug: 'mains',
    description: 'Prime cuts, flame-kissed seafood, and slow-braised signature specialties.',
    icon: 'Flame',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
    displayOrder: 3,
  },
  {
    name: 'Handcrafted Pastas',
    slug: 'pastas',
    description: 'Fresh bronze-die cut pasta tossed in rich authentic Italian reductions.',
    icon: 'CookingPot',
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    displayOrder: 4,
  },
  {
    name: 'Decadent Desserts',
    slug: 'desserts',
    description: 'Exquisite pastry creations and velvety confectioneries crafted daily.',
    icon: 'Cake',
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=600&q=80',
    displayOrder: 5,
  },
  {
    name: 'Craft Beverages & Wines',
    slug: 'beverages',
    description: 'Botanical mocktails, cold-pressed infusions, and artisanal refreshments.',
    icon: 'Wine',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
    displayOrder: 6,
  },
];

export const foodsData = [
  // Starters
  {
    name: 'Truffle Burrata & Heirloom Bruschetta',
    categorySlug: 'starters',
    description: 'Creamy artisanal Puglia burrata on toasted sourdough with heirloom cherry tomatoes, basil oil, and aged balsamic glaze.',
    price: 16.50,
    image: 'https://images.unsplash.com/photo-1592417817098-8f3d6ef23049?auto=format&fit=crop&w=800&q=80',
    dietary: ['vegetarian', 'chef-special'],
    prepTime: 12,
    calories: 420,
    rating: 4.9,
    reviewsCount: 38,
    isAvailable: true,
    isFeatured: true,
    ingredients: ['Burrata cheese', 'Heirloom tomatoes', 'Sourdough', 'Truffle oil', 'Micro basil'],
  },
  {
    name: 'Crispy Calamari Fritti',
    categorySlug: 'starters',
    description: 'Golden tender squid rings lightly dusted with smoked paprika, served with caper-lemon aioli and fresh herbs.',
    price: 15.00,
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=800&q=80',
    dietary: ['spicy'],
    prepTime: 14,
    calories: 380,
    rating: 4.7,
    reviewsCount: 24,
    isAvailable: true,
    isFeatured: false,
    ingredients: ['Calamari', 'Smoked paprika', 'Lemon aioli', 'Parsley', 'Sea salt'],
  },
  {
    name: 'Avocado Tartare & Wonton Crisps',
    categorySlug: 'starters',
    description: 'Hand-diced Hass avocado, shallots, sesame ponzu dressing, and crispy lotus root & wonton wafers.',
    price: 14.00,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    dietary: ['vegan', 'gluten-free'],
    prepTime: 10,
    calories: 290,
    rating: 4.8,
    reviewsCount: 19,
    isAvailable: true,
    isFeatured: false,
    ingredients: ['Avocado', 'Ponzu', 'Shallots', 'Sesame seeds', 'Lotus crisps'],
  },

  // Pizzas
  {
    name: 'Black Truffle & Wild Mushroom Pizza',
    categorySlug: 'pizzas',
    description: 'Fontina & mozzarella cheese blend, sautéed chanterelles & shiitake, shaved black winter truffle, and thyme.',
    price: 24.50,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
    dietary: ['vegetarian', 'chef-special'],
    prepTime: 18,
    calories: 820,
    rating: 5.0,
    reviewsCount: 65,
    isAvailable: true,
    isFeatured: true,
    ingredients: ['Sourdough base', 'Wild mushrooms', 'Black truffle puree', 'Fontina', 'Fior di latte'],
  },
  {
    name: 'San Daniele Prosciutto & Arugula Pizza',
    categorySlug: 'pizzas',
    description: 'San Marzano DOP tomato sauce, fresh buffalo mozzarella, 24-month prosciutto di Parma, wild baby arugula, and shaved Parmigiano-Reggiano.',
    price: 23.00,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80',
    dietary: [],
    prepTime: 16,
    calories: 780,
    rating: 4.9,
    reviewsCount: 42,
    isAvailable: true,
    isFeatured: true,
    ingredients: ['San Marzano tomatoes', 'Buffalo mozzarella', 'Prosciutto di Parma', 'Arugula', 'Parmigiano'],
  },
  {
    name: 'Spicy Diavola & Nduja Flatbread',
    categorySlug: 'pizzas',
    description: 'Fiery Calabrian nduja sausage, spicy soppressata, chili-infused organic honey drizzle, and fresh oregano.',
    price: 22.00,
    image: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&w=800&q=80',
    dietary: ['spicy'],
    prepTime: 15,
    calories: 850,
    rating: 4.8,
    reviewsCount: 31,
    isAvailable: true,
    isFeatured: false,
    ingredients: ['Spicy soppressata', 'Nduja', 'Hot honey', 'Mozzarella', 'Oregano'],
  },

  // Mains & Grills
  {
    name: 'Prime Dry-Aged Ribeye Steak (12oz)',
    categorySlug: 'mains',
    description: '45-day dry-aged USDA Prime ribeye grilled over oak embers, served with roasted garlic butter, confit bone marrow, and rosemary fingerling potatoes.',
    price: 44.00,
    image: 'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=800&q=80',
    dietary: ['chef-special', 'gluten-free'],
    prepTime: 25,
    calories: 950,
    rating: 5.0,
    reviewsCount: 88,
    isAvailable: true,
    isFeatured: true,
    ingredients: ['Dry-aged ribeye', 'Garlic butter', 'Bone marrow', 'Rosemary potatoes', 'Maldon salt'],
  },
  {
    name: 'Pan-Seared Chilean Sea Bass',
    categorySlug: 'mains',
    description: 'Sustainably caught sea bass fillet on saffron risotto, sautéed baby broccolini, and a delicate citrus beurre blanc.',
    price: 38.50,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80',
    dietary: ['gluten-free', 'chef-special'],
    prepTime: 22,
    calories: 640,
    rating: 4.9,
    reviewsCount: 52,
    isAvailable: true,
    isFeatured: true,
    ingredients: ['Chilean sea bass', 'Saffron risotto', 'Broccolini', 'Citrus beurre blanc'],
  },
  {
    name: 'Rosemary & Herb Crusted Lamb Chops',
    categorySlug: 'mains',
    description: 'New Zealand pasture-raised lamb chops grilled to medium pink, with parsnip silk purée, glazed baby carrots, and mint-port reduction.',
    price: 36.00,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    dietary: ['gluten-free'],
    prepTime: 24,
    calories: 720,
    rating: 4.8,
    reviewsCount: 29,
    isAvailable: true,
    isFeatured: false,
    ingredients: ['Lamb cutlets', 'Parsnip purée', 'Mint port reduction', 'Baby carrots'],
  },

  // Pastas
  {
    name: 'Handcrafted Tagliolini al Tartufo',
    categorySlug: 'pastas',
    description: 'Silky egg ribbon pasta tossed in emulsion of cultured French butter, 36-month aged Reggiano, and copious fresh winter black truffle shavings.',
    price: 28.00,
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281707?auto=format&fit=crop&w=800&q=80',
    dietary: ['vegetarian', 'chef-special'],
    prepTime: 16,
    calories: 680,
    rating: 4.9,
    reviewsCount: 47,
    isAvailable: true,
    isFeatured: true,
    ingredients: ['Fresh egg tagliolini', 'French butter', 'Parmigiano Reggiano', 'Black winter truffle'],
  },
  {
    name: 'Wild Boar Ragù Pappardelle',
    categorySlug: 'pastas',
    description: 'Broad Tuscan ribbon pasta draped in 8-hour braised wild boar simmered with Chianti wine, juniper berries, and fragrant rosemary.',
    price: 26.50,
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80',
    dietary: [],
    prepTime: 18,
    calories: 740,
    rating: 4.9,
    reviewsCount: 34,
    isAvailable: true,
    isFeatured: false,
    ingredients: ['Pappardelle pasta', 'Wild boar slow braise', 'Chianti wine', 'Juniper berries'],
  },
  {
    name: 'Lobster & Ricotta Ravioli',
    categorySlug: 'pastas',
    description: 'Pillow-soft pasta filled with sweet Maine lobster and lemon-infused ricotta in a luscious brandy bisque emulsion.',
    price: 32.00,
    image: 'https://images.unsplash.com/photo-1587740896339-96a76170508d?auto=format&fit=crop&w=800&q=80',
    dietary: ['chef-special'],
    prepTime: 20,
    calories: 610,
    rating: 4.9,
    reviewsCount: 41,
    isAvailable: true,
    isFeatured: false,
    ingredients: ['Maine lobster', 'Ricotta', 'Brandy shellfish bisque', 'Tarragon'],
  },

  // Desserts
  {
    name: 'Valrhona Chocolate Lava Dome',
    categorySlug: 'desserts',
    description: 'Warm molten single-origin dark chocolate cake flowing with Madagascar vanilla bean gelato and gold leaf garnish.',
    price: 13.50,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80',
    dietary: ['vegetarian', 'chef-special'],
    prepTime: 12,
    calories: 540,
    rating: 5.0,
    reviewsCount: 76,
    isAvailable: true,
    isFeatured: true,
    ingredients: ['Valrhona 70% dark chocolate', 'Madagascar vanilla gelato', 'Raspberry coulis'],
  },
  {
    name: 'Artisanal Classic Tiramisù',
    categorySlug: 'desserts',
    description: 'Espresso-soaked Savoiardi ladyfingers layered with whipped mascarpone cream, dark Marsala wine, and Dutch cocoa dust.',
    price: 12.00,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=800&q=80',
    dietary: ['vegetarian'],
    prepTime: 8,
    calories: 460,
    rating: 4.8,
    reviewsCount: 39,
    isAvailable: true,
    isFeatured: false,
    ingredients: ['Mascarpone', 'Savoiardi', 'Espresso', 'Marsala', 'Valrhona cocoa'],
  },
  {
    name: 'Passionfruit & Mango Panna Cotta',
    categorySlug: 'desserts',
    description: 'Silky Bourbon vanilla bean panna cotta topped with vibrant exotic passionfruit gelée and caramelized pistachio crumb.',
    price: 11.50,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80',
    dietary: ['gluten-free', 'vegetarian'],
    prepTime: 8,
    calories: 340,
    rating: 4.7,
    reviewsCount: 22,
    isAvailable: true,
    isFeatured: false,
    ingredients: ['Heavy cream', 'Passionfruit curd', 'Pistachio', 'Vanilla bean'],
  },

  // Beverages
  {
    name: 'Smoked Rosemary Citrus Fizz',
    categorySlug: 'beverages',
    description: 'Fresh ruby red grapefruit juice, cold-pressed yuzu, botanical tonic, infused with torched wild rosemary smoke.',
    price: 9.50,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    dietary: ['vegan', 'gluten-free'],
    prepTime: 5,
    calories: 120,
    rating: 4.8,
    reviewsCount: 18,
    isAvailable: true,
    isFeatured: true,
    ingredients: ['Ruby grapefruit', 'Yuzu', 'Tonic', 'Smoked rosemary', 'Agave'],
  },
  {
    name: 'Hibiscus Berry Botanical Elixir',
    categorySlug: 'beverages',
    description: 'Brewed wild hibiscus petals, muddled organic blackberries, fresh mint sprigs, sparkling artisan mineral water.',
    price: 8.50,
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=800&q=80',
    dietary: ['vegan', 'gluten-free'],
    prepTime: 5,
    calories: 90,
    rating: 4.9,
    reviewsCount: 26,
    isAvailable: true,
    isFeatured: false,
    ingredients: ['Hibiscus tea', 'Blackberries', 'Mint', 'Sparkling water'],
  },
  {
    name: 'Kyoto Ceremonial Iced Matcha Latte',
    categorySlug: 'beverages',
    description: 'First-harvest Uji ceremonial matcha whisked with Madagascar vanilla and your choice of creamy oat or whole milk.',
    price: 8.00,
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=800&q=80',
    dietary: ['vegetarian', 'gluten-free'],
    prepTime: 5,
    calories: 140,
    rating: 4.8,
    reviewsCount: 33,
    isAvailable: true,
    isFeatured: false,
    ingredients: ['Uji matcha', 'Oat milk', 'Vanilla syrup', 'Crushed ice'],
  },
];

export const tablesData = [
  { tableNumber: 'T-01', capacity: 2, location: 'indoor', shape: 'round', description: 'Cozy romantic corner table near the wine cellar' },
  { tableNumber: 'T-02', capacity: 2, location: 'indoor', shape: 'square', description: 'Window view table with natural evening lighting' },
  { tableNumber: 'T-03', capacity: 4, location: 'indoor', shape: 'rectangle', description: 'Main dining hall center table' },
  { tableNumber: 'T-04', capacity: 4, location: 'indoor', shape: 'booth', description: 'Plush velvet booth with privacy partition' },
  { tableNumber: 'T-05', capacity: 6, location: 'indoor', shape: 'rectangle', description: 'Family dining table near open view kitchen' },
  { tableNumber: 'P-01', capacity: 2, location: 'outdoor_patio', shape: 'round', description: 'Al fresco garden table with floral pergola' },
  { tableNumber: 'P-02', capacity: 4, location: 'outdoor_patio', shape: 'square', description: 'Lantern-lit garden patio seating' },
  { tableNumber: 'R-01', capacity: 2, location: 'rooftop', shape: 'round', description: 'Panoramic city skyline view for couples' },
  { tableNumber: 'R-02', capacity: 6, location: 'rooftop', shape: 'rectangle', description: 'Sunset lounge table with firepit access' },
  { tableNumber: 'VIP-01', capacity: 8, location: 'vip_lounge', shape: 'rectangle', description: 'Private dining room with dedicated sommelier service' },
];
